site_name: DevTools CLI Documentation
site_dir: ../dist/docs
repo_url: https://bitbucket.org/phase2tech/_devtools_vm
site_author: Phase2
google_analytics: ['UA-305109-83', 'readthedocs.org/projects/devtools']
theme: readthedocs
docs_dir: .
pages:
  - 'Home': 'index.md'
  - 'Introduction': '00_INTRO.md'
  - 'Tool Chain': '10_TOOLCHAIN.md'
  - 'Project Setup': '20_PROJECT_SETUP.md'
  - 'Project Usage': '30_PROJECT_USAGE.md'
  - 'Integration': '40_INTEGRATION.md'
  - 'Troubleshooting': '50_TROUBLESHOOTING.md'
  - 'FAQ': '60_FAQ.md'
  - 'LINUX': '99_LINUX.md'
